//------------------------------------------------------------------------
// Copyright(c) 2024 Oscarde.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"PDF.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"PDF VST3 (64Bit)"
#else
#define stringFileDescription	"PDF VST3"
#endif
#define stringCompanyName		"Oscarde\0"
#define stringLegalCopyright	"Copyright(c) 2024 Oscarde."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
